/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vNEiNAMenP6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"

function PropertyCard({ imageSrc, price, title, address, beds, baths, area, description }) {
  return (
    <Card className="flex flex-col md:flex-row p-4 gap-4">
      <img src="/placeholder.svg" alt={title} className="w-full md:w-1/3 rounded-lg object-cover" />
      <div className="flex flex-col flex-1">
        <div className="flex justify-between items-center">
          <Badge variant="secondary">Featured</Badge>
          <Badge variant="destructive">Rent</Badge>
        </div>
        <div className="mt-2">
          <h3 className="text-lg font-semibold">{title}</h3>
          <p className="text-sm text-muted-foreground">{address}</p>
          <p className="text-sm text-muted-foreground">
            Beds: {beds} Baths: {baths} {area} SQM
          </p>
          <p className="text-sm text-muted-foreground">{description}</p>
        </div>
        <div className="flex justify-between items-center mt-4">
          <div className="text-lg font-bold">${price}</div>
          <Button variant="outline">Details</Button>
        </div>
      </div>
    </Card>
  )
}
export function ListView() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center justify-between h-16 px-4 border-b">
        <div className="flex items-center space-x-4">
          <div className="text-2xl font-bold">LOGO</div>
          <nav className="hidden md:flex space-x-4">
            <Link href="#" className="text-lg" prefetch={false}>
              For Sale
            </Link>
            <Link href="#" className="text-lg" prefetch={false}>
              To Rent
            </Link>
            <Link href="#" className="text-lg" prefetch={false}>
              New Developments
            </Link>
            <Link href="#" className="text-lg" prefetch={false}>
              Showdays
            </Link>
            <Link href="#" className="text-lg" prefetch={false}>
              Agencies
            </Link>
            <Link href="#" className="text-lg" prefetch={false}>
              Blog
            </Link>
          </nav>
        </div>
        <div className="relative">
          <Button variant="ghost" size="icon" className="rounded-full">
            <UserIcon className="h-6 w-6" />
          </Button>
          <div className="absolute right-0 mt-2 w-48 bg-white border rounded-md shadow-lg">
            <Link href="#" className="block px-4 py-2" prefetch={false}>
              Signup
            </Link>
            <Link href="#" className="block px-4 py-2" prefetch={false}>
              Login
            </Link>
          </div>
        </div>
      </header>
      <main className="flex flex-1 p-4">
        <aside className="w-full md:w-1/4 p-4 border-r">
          <Select>
            <SelectTrigger id="property-types">
              <SelectValue placeholder="Property Types" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="house">House</SelectItem>
              <SelectItem value="apartment">Apartment</SelectItem>
            </SelectContent>
          </Select>
          <div className="mt-4">
            <Input placeholder="Suburb, City, Province, Country" />
            <div className="grid grid-cols-2 gap-4 mt-4">
              <Input placeholder="Min. Price" />
              <Input placeholder="Max. Price" />
              <Input placeholder="Min. Beds" />
              <Input placeholder="Max. Beds" />
            </div>
          </div>
        </aside>
        <section className="flex-1 p-4">
          <div className="flex justify-between items-center mb-4">
            <div>Sort by:</div>
            <div>10 Search Results</div>
          </div>
          <div className="space-y-4">
            <div />
            <div />
            <div />
          </div>
        </section>
      </main>
    </div>
  )
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
