/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZQ0Tzc1XjJ2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Property } from "@/lib/types";
import { EnquiryForm } from "./enquiry-form";

type PropertyDetailProps = {
  property: Property;
};


export function PropertyDetail({
  property
}:  PropertyDetailProps
) {

  return (
    <div className="min-h-screen bg-gray-100">
      
      <main className="container mx-auto py-8 px-6">
        <div className="flex flex-col lg:flex-row lg:space-x-8">
          <div className="flex-1 bg-white p-6">
            <h1 className="text-3xl font-bold">{property.title}</h1>
            <p className="text-gray-600">{property.address}</p>
            <div className="text-2xl font-bold mt-4">${property.price}/mo</div>
            <div className="mt-4">
              <img src={property.images[0].filePath} alt="Home Image" className="w-full h-auto" />
            </div>
            <div className="mt-4 flex space-x-2">
              {property.images.map(image => (
                <img src={image.filePath} alt="Thumbnail" className="w-24 h-24" />
              ))}
              
            </div>
            <div className="mt-8">
              <h2 className="text-2xl font-bold">Description</h2>
              <p className="text-gray-700 mt-2">
                {property.description}
              </p>
              
            </div>
            <div className="mt-8">
              <h2 className="text-2xl font-bold">Property Details</h2>
              <div className="grid grid-cols-2 gap-4 mt-4">
                <div>
                  <p className="text-gray-700">
                    <strong>Property ID:</strong> {property.id}
                  </p>
                  <p className="text-gray-700">
                    <strong>Property Size:</strong> {property.propertySize}
                  </p>
                 
                </div>
                <div>
                  <p className="text-gray-700">
                    <strong>Property Type:</strong> {property.type}
                  </p>
                  <p className="text-gray-700">
                    <strong>Year Built:</strong> {property.yearBuilt}
                  </p>
                  
                </div>
                <div>
                  <p className="text-gray-700">
                    <strong>Property Status:</strong> {property.status}
                  </p>
                  <p className="text-gray-700">
                    <strong>Property Price:</strong> ${property.price}
                  </p>
                 
                </div>
              </div>
            </div>
            <div className="mt-8">
              <h2 className="text-2xl font-bold">Property Features</h2>
              <p className="text-gray-700 mt-2">Feature details here...</p>
            </div>
          </div>
          <aside className="w-full lg:w-1/3">
            <div className="bg-white shadow p-6">
              <img src="/placeholder.svg" alt="Housing Logo" className="w-24 h-24 mx-auto" />
              <h3 className="text-xl font-bold text-center mt-4">Housing Investment</h3>
              <div className="mt-4 flex flex-col space-y-2">
                <Button variant="outline" className="w-full">
                  Whatsapp Agent
                </Button>
                <Button variant="outline" className="w-full">
                  Call Agent
                </Button>
              </div>
              <EnquiryForm listingId={property.id} />
              <p className="text-xs text-gray-600 text-center mt-4">
                By sending enquiry messages, you agree to Sold.co.nz's{" "}
                <Link href="#" className="text-blue-600" prefetch={false}>
                  Terms & Conditions
                </Link>
              </p>
            </div>
          </aside>
        </div>
      </main>
      
    </div>
  )
}
