/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tlPKVC0ikpa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Test2() {
  return (
    <div className="min-h-screen bg-gray-100">
      
      <section className="bg-gray-200 py-12 md:py-16">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 md:space-x-4 md:space-y-0 md:flex-row">
            <button className="bg-red-500 text-white px-4 py-2 rounded w-full md:w-auto">For Sale</button>
            <button className="bg-gray-300 text-gray-700 px-4 py-2 rounded w-full md:w-auto">To Rent</button>
          </div>
          <div className="mt-6 flex flex-col items-center justify-center space-y-4 md:space-x-4 md:space-y-0 md:flex-row">
            <input
              type="text"
              placeholder="Property Types"
              className="border border-gray-300 px-4 py-2 rounded w-full md:w-48"
            />
            <input
              type="text"
              placeholder="Suburb, City, Province, Country"
              className="border border-gray-300 px-4 py-2 rounded w-full md:w-96"
            />
            <button className="bg-red-500 text-white px-4 py-2 rounded w-full md:w-auto">SEARCH</button>
          </div>
        </div>
      </section>
      <section className="px-4 md:px-6">
        <h2 className="text-2xl font-bold mb-6">Properties For Sale</h2>
        <div className="flex overflow-x-auto snap-x snap-mandatory space-x-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex-shrink-0 bg-white rounded shadow p-4 snap-center w-[300px]">
              <img src="/placeholder.svg" alt="Property" className="w-full h-48 object-cover rounded" />
              <div className="mt-4">
                <h3 className="text-lg font-semibold">Property Type</h3>
                <p className="text-gray-600">Luxury Family Home</p>
                <p className="text-gray-600">83 Hindhead Avenue, Chisipite, Harare</p>
                <p className="text-gray-600">Beds: 2 Baths: 1 2000 SQM</p>
                <button className="mt-4 bg-red-500 text-white px-4 py-2 rounded">Details</button>
              </div>
            </div>
          ))}
        </div>
        <div className="flex justify-center mt-4 space-x-2">
          <div className="w-2 h-2 bg-gray-400 rounded-full" />
          <div className="w-2 h-2 bg-gray-400 rounded-full" />
          <div className="w-2 h-2 bg-gray-400 rounded-full" />
        </div>
      </section>
      <section className="container mx-auto py-12">
        <h2 className="text-2xl font-bold mb-6">Properties For Rent</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white rounded shadow p-4">
              <img src="/placeholder.svg" alt="Property" className="w-full h-48 object-cover rounded" />
              <div className="mt-4">
                <h3 className="text-lg font-semibold">Property Type</h3>
                <p className="text-gray-600">Luxury Family Home</p>
                <p className="text-gray-600">83 Hindhead Avenue, Chisipite, Harare</p>
                <p className="text-gray-600">Beds: 2 Baths: 1 2000 SQM</p>
                <button className="mt-4 bg-red-500 text-white px-4 py-2 rounded">Details</button>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section className="bg-gray-100 py-12">
        <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="bg-white rounded shadow p-6 text-center">
            <img src="/placeholder.svg" alt="Buy a Property" className="mx-auto mb-4" />
            <h3 className="text-lg font-semibold">Buy a Property</h3>
            <p className="text-gray-600">
              Find your place with an immersive photo experience and the most listings, including things you won't find
              anywhere else.
            </p>
            <button className="mt-4 bg-red-500 text-white px-4 py-2 rounded">Browse Properties For Sale</button>
          </div>
          <div className="bg-white rounded shadow p-6 text-center">
            <img src="/placeholder.svg" alt="Sell a Property" className="mx-auto mb-4" />
            <h3 className="text-lg font-semibold">Sell a Property</h3>
            <p className="text-gray-600">
              Find your place with an immersive photo experience and the most listings, including things you won't find
              anywhere else.
            </p>
            <button className="mt-4 bg-red-500 text-white px-4 py-2 rounded">See your options</button>
          </div>
          <div className="bg-white rounded shadow p-6 text-center">
            <img src="/placeholder.svg" alt="Rent a Property" className="mx-auto mb-4" />
            <h3 className="text-lg font-semibold">Rent a Property</h3>
            <p className="text-gray-600">
              Find your place with an immersive photo experience and the most listings, including things you won't find
              anywhere else.
            </p>
            <button className="mt-4 bg-red-500 text-white px-4 py-2 rounded">Find Rentals</button>
          </div>
        </div>
      </section>
      <footer className="bg-blue-900 py-6">
        <div className="container mx-auto flex items-center justify-between text-white">
          <p>© 2024 Sold.co.zw. All rights reserved.</p>
          <div className="flex space-x-4">
            <a href="#" className="hover:underline">
              Privacy Policy
            </a>
            <a href="#" className="hover:underline">
              Terms of Service
            </a>
          </div>
        </div>
      </footer>
    </div>
  )
}
